services:
  server:
    image: docker.superkoch.com.br/painel-lojas:latest
    build: frontend
    volumes:
        - /home/aplicacoes/logs/painel-lojas:/app/logs # TODO: Criar pasta nos logs
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - CONSINCO_DB_USER=$CONSINCO_DB_USER
      - CONSINCO_DB_PASSWORD=$CONSINCO_DB_PASSWORD
      - CONSINCO_DB_CONNECT_STRING=$CONSINCO_DB_CONNECT_STRING
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    networks:
      - network_custom1
networks:
  network_custom1:
    external: true
